// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQPPmjL0KNZ5QIgbYUUhFkNbZm1sKg_2U',
    appId: '1:374423276406:web:c41968ee47ca0eeca9c857',
    messagingSenderId: '374423276406',
    projectId: 'redl-3bf5a',
    authDomain: 'redl-3bf5a.firebaseapp.com',
    storageBucket: 'redl-3bf5a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOpf0S8s87CgMjgvTlFpn9RxtMQVLpRPo',
    appId: '1:374423276406:android:e83962f5c94af174a9c857',
    messagingSenderId: '374423276406',
    projectId: 'redl-3bf5a',
    storageBucket: 'redl-3bf5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy2dte1S5c6Z39sDmPT4bTgs1e9RQwn3I',
    appId: '1:374423276406:ios:d088368c85e1ba7aa9c857',
    messagingSenderId: '374423276406',
    projectId: 'redl-3bf5a',
    storageBucket: 'redl-3bf5a.firebasestorage.app',
    iosBundleId: 'com.example.redl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy2dte1S5c6Z39sDmPT4bTgs1e9RQwn3I',
    appId: '1:374423276406:ios:d088368c85e1ba7aa9c857',
    messagingSenderId: '374423276406',
    projectId: 'redl-3bf5a',
    storageBucket: 'redl-3bf5a.firebasestorage.app',
    iosBundleId: 'com.example.redl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQPPmjL0KNZ5QIgbYUUhFkNbZm1sKg_2U',
    appId: '1:374423276406:web:1cc6ddc4fed12342a9c857',
    messagingSenderId: '374423276406',
    projectId: 'redl-3bf5a',
    authDomain: 'redl-3bf5a.firebaseapp.com',
    storageBucket: 'redl-3bf5a.firebasestorage.app',
  );

}